name: telegram message
on:
  pull_request_review_comment:
    types: [created]
  pull_request:
    types: [opened, ready_for_review, reopened]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - uses: uesteibar/reviewer-lottery@v2
        if: ${{ github.event_name == 'pull_request' }}
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: send telegram message on pull req
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}

          message: |
            ${{ github.actor }} ${{github.event.action}} ${{github.event_name}} 

            ${{ github.event.pull_request.requested_reviewers[0].avatar_url }}
            reviewer: ${{ github.event.pull_request.requested_reviewers[0].name }}

            See please: https://github.com/${{ github.repository }}/pull/${{github.event.pull_request.number}}

      
    